apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example-service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service1
  template:
    metadata:
      labels:
        app: example-service1
    spec:
      containers:
      - name: example-service1
        image: quay.io/dwojciec/example-service1:v0.2.2
        ports:
        - containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: example-service1
spec:
  selector:
    app: example-service1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
